services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      BASE_URL: ${BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - '3000:3000'
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 --timeout=30 &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        node dist/src/main.js
      "

volumes:
  pgdata:
